//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fájl_áthelyező.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\bony_labor\\ToFonix\\lab.msg")]
        public string sourceFile {
            get {
                return ((string)(this["sourceFile"]));
            }
            set {
                this["sourceFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\bony_labor\\ToFonix\\lab.sem")]
        public string sourceSemFile {
            get {
                return ((string)(this["sourceSemFile"]));
            }
            set {
                this["sourceSemFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("s:\\ToFonix")]
        public string destinationDir {
            get {
                return ((string)(this["destinationDir"]));
            }
            set {
                this["destinationDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int freqM {
            get {
                return ((int)(this["freqM"]));
            }
            set {
                this["freqM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int freqS {
            get {
                return ((int)(this["freqS"]));
            }
            set {
                this["freqS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("s:\\FromFonix\\lab.msg")]
        public string sourceBonyFile {
            get {
                return ((string)(this["sourceBonyFile"]));
            }
            set {
                this["sourceBonyFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("s:\\FromFonix\\lab.sem")]
        public string sourceBonySemFile {
            get {
                return ((string)(this["sourceBonySemFile"]));
            }
            set {
                this["sourceBonySemFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\bony_labor\\FromFonix")]
        public string destinationBonyDir {
            get {
                return ((string)(this["destinationBonyDir"]));
            }
            set {
                this["destinationBonyDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool send {
            get {
                return ((bool)(this["send"]));
            }
            set {
                this["send"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool receive {
            get {
                return ((bool)(this["receive"]));
            }
            set {
                this["receive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n:\\szszard.msg")]
        public string sourcePecsFile {
            get {
                return ((string)(this["sourcePecsFile"]));
            }
            set {
                this["sourcePecsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n:\\szszard.sem")]
        public string sourcePecsSemFile {
            get {
                return ((string)(this["sourcePecsSemFile"]));
            }
            set {
                this["sourcePecsSemFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\pte_labor\\teszt\\in")]
        public string destinationPecsDir {
            get {
                return ((string)(this["destinationPecsDir"]));
            }
            set {
                this["destinationPecsDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\pte_labor\\teszt\\out\\szszard.msg")]
        public string sourcePecsLabFile {
            get {
                return ((string)(this["sourcePecsLabFile"]));
            }
            set {
                this["sourcePecsLabFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\pte_labor\\teszt\\out\\szszard.sem")]
        public string sourcePecsLabSemFile {
            get {
                return ((string)(this["sourcePecsLabSemFile"]));
            }
            set {
                this["sourcePecsLabSemFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m:\\")]
        public string destinationPecsLabDir {
            get {
                return ((string)(this["destinationPecsLabDir"]));
            }
            set {
                this["destinationPecsLabDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool psend {
            get {
                return ((bool)(this["psend"]));
            }
            set {
                this["psend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool preceive {
            get {
                return ((bool)(this["preceive"]));
            }
            set {
                this["preceive"] = value;
            }
        }
    }
}
